user       root;  ## Default: nobody
worker_processes  1;  ## Default: 1
error_log  logs/error.log;
pid        logs/nginx.pid;
#worker_rlimit_nofile 8192;

events {
  worker_connections  524;  ## Default: 1024
}

http {
  include    conf/mime.types;

  index    index.html index.htm index.php;

  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   logs/access.log  main;
  sendfile     on;
  tcp_nopush   on;
  server_names_hash_bucket_size 128; # this seems to be required for some vhosts

      server {
        listen 443 ssl;

        server_name localhost;

        ssl_certificate     /mnt/sdcard/extra_binary/static-bin-armv7/nginx/nginx/1.19.4/cert/nginx.crt;
        ssl_certificate_key /mnt/sdcard/extra_binary/static-bin-armv7/nginx/nginx/1.19.4/cert/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
      #     proxy_pass https://192.168.1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}


     location /cgi-bin/ {

          # Disable gzip (it makes scripts feel slower since they have to complete
          # before getting gzipped)
          #gzip off;

          # Set the root to /usr/lib (inside this location this means that we are
          # giving access to the files under /usr/lib/cgi-bin)
          #root /usr/lib;

          # Fastcgi socket
          fastcgi_pass  unix:/tmp/fcgiwrap.sock;

	  # Fastcgi parameters, include the standard ones
	  include conf/fastcgi.conf;

         }

    location /php/ {

        #proxy_redirect          off;
        #proxy_set_header        Host            $host;
        #proxy_set_header        X-Real-IP       $remote_addr;
        #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        #client_max_body_size    10m;
        #client_body_buffer_size 128k;
        #proxy_connect_timeout   90;
        #proxy_send_timeout      90;
        ##proxy_read_timeout      90;
        #proxy_buffers           32 4k;

               proxy_pass http://127.0.0.1:8081/;

        }

  }
}

